version: '3.8'

services:
  gateway:
    image: nikhilkumar12/hive-gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - USER_PORT=3001
      - POST_PORT=3002
      - CHAT_PORT=3003
    depends_on:
      - users
      - posts
      - chats
      # - redis

  users:
    image: nikhilkumar12/hive-user-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - PORT=3001

  posts:
    image: nikhilkumar12/hive-post-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - PORT=3002

  chats:
    image: nikhilkumar12/hive-chat-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - PORT=3003

  # redis:
  #   image: "redis/redis-stack:latest"
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"
